# inherit_from:
  # - rubocop-todo.yml

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RescueModifier:
  Enabled: false
