language: ruby
script:
  - 'bundle exec rubocop'
  - 'bundle exec rake test:unit'
sudo: false
matrix:
  include:
    - rvm: 1.9
      gemfile: gemfiles/ruby_1.9.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/HEAD.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/HEAD.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/HEAD.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/HEAD.gemfile
